name: Docker Build

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build

    - name: Push image
      run: |
        JUDGE_IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/judge
        WEB_IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/web

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        echo JUDGE_IMAGE_ID=$JUDGE_IMAGE_ID
        echo WEB_IMAGE_ID=$WEB_IMAGE_ID
        echo VERSION=$VERSION

        docker tag $JUDGE_IMAGE_ID $JUDGE_IMAGE_ID:$VERSION
        docker tag $WEB_IMAGE_ID $WEB_IMAGE_ID:$VERSION
        docker push $JUDGE_IMAGE_ID:$VERSION
        docker push $WEB_IMAGE_ID:$VERSION